# mypy: allow-untyped-defs, allow-incomplete-defs, allow-any-generics
# fmt: off

from typing import Callable, ClassVar, Dict, List, Optional, Tuple, Union, overload

YARAMOD_VERSION: str
YARAMOD_VERSION_MAJOR: int
YARAMOD_VERSION_MINOR: int
YARAMOD_VERSION_PATCH: int
YARA_SYNTAX_VERSION: str

class AllExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class AndExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class AnyExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ArrayAccessExpression(IdExpression):
    accessor: Expression
    array: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class ArraySymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def element_type(self) -> ExpressionType: ...
    @property
    def structure(self) -> Symbol: ...

class AsciiStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...

class Base64StringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def has_alphabet(self) -> bool: ...

class Base64WideStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def has_alphabet(self) -> bool: ...

class BinaryOpExpression(Expression):
    left_operand: Expression
    right_operand: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class BitwiseAndExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class BitwiseNotExpression(UnaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class BitwiseOrExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class BitwiseXorExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class BoolLiteralExpression(_BoolLiteralExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ContainsExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class DefinedExpression(UnaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class DictionarySymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def element_type(self) -> ExpressionType: ...
    @property
    def structure(self) -> Symbol: ...

class DivideExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class DoubleLiteralExpression(_DoubleLiteralExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class EndsWithExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class EntrypointExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class EqExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class Expression:
    def __init__(self, *args, **kwargs) -> None: ...
    def accept(self, visitor: Visitor) -> Union[Expression,VisitAction]: ...
    def exchange_tokens(self, other: Expression) -> None: ...
    def clone(self, target: TokenStream) -> Expression: ...
    def get_text(self, indent: str = ...) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def token_first(self) -> Token: ...
    @property
    def token_last(self) -> Token: ...
    @property
    def tokenstream(self) -> TokenStream: ...
    @property
    def uid(self) -> int: ...

class ExpressionType:
    __members__: ClassVar[dict] = ...  # read-only
    Bool: ClassVar[ExpressionType] = ...
    Float: ClassVar[ExpressionType] = ...
    Int: ClassVar[ExpressionType] = ...
    Object: ClassVar[ExpressionType] = ...
    Regexp: ClassVar[ExpressionType] = ...
    String: ClassVar[ExpressionType] = ...
    Undefined: ClassVar[ExpressionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Features:
    __members__: ClassVar[dict] = ...  # read-only
    AllCurrent: ClassVar[Features] = ...
    Avast: ClassVar[Features] = ...
    AvastOnly: ClassVar[Features] = ...
    Basic: ClassVar[Features] = ...
    Everything: ClassVar[Features] = ...
    VirusTotal: ClassVar[Features] = ...
    VirusTotalOnly: ClassVar[Features] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __setstate__(self, state: int) -> None: ...
    def __xor__(self, other: object) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class FilesizeExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ForArrayExpression(ForExpression):
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class ForDictExpression(ForExpression):
    id1: str
    id2: str
    def __init__(self, *args, **kwargs) -> None: ...

class ForExpression(Expression):
    body: Expression
    iterable: Expression
    variable: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class ForStringExpression(ForExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class FullwordStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...

class FunctionCallExpression(IdExpression):
    arguments: List[Expression]
    function: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class FunctionSymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def argument_names(self) -> List[List[str]]: ...
    @property
    def documentations(self) -> List[str]: ...
    @property
    def overloads(self) -> List[List[ExpressionType]]: ...
    @property
    def return_type(self) -> ExpressionType: ...

class GeExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class GtExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class HexStringUnit:
    """Base class for hex string units (not directly exposed to Python, used for type hints)."""
    ...

class HexString(String):
    def __init__(self, *args, **kwargs) -> None: ...

class IdExpression(Expression):
    symbol: Symbol
    def __init__(self, *args, **kwargs) -> None: ...

class IdWildcardExpression(Expression):
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class IcontainsExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class IendsWithExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class IequalsExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class IstartsWithExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class IntFunctionEndianness:
    __members__: ClassVar[dict] = ...  # read-only
    Big: ClassVar[IntFunctionEndianness] = ...
    Little: ClassVar[IntFunctionEndianness] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class IntFunctionExpression(Expression):
    argument: Expression
    function: str
    def __init__(self, *args, **kwargs) -> None: ...

class IntLiteralExpression(_IntLiteralExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class IntMultiplier:
    __members__: ClassVar[dict] = ...  # read-only
    Empty: ClassVar[IntMultiplier] = ...
    Kilobytes: ClassVar[IntMultiplier] = ...
    Megabytes: ClassVar[IntMultiplier] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class IterableExpression(Expression):
    elements: List[Expression]
    def __init__(self, *args, **kwargs) -> None: ...

class KeywordExpression(Expression):
    def __init__(self, *args, **kwargs) -> None: ...

class LeExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class Literal:
    @overload
    def __init__(self, value: str) -> None: ...
    @overload
    def __init__(self, value: bool) -> None: ...
    @overload
    def __init__(self, value: int) -> None: ...
    @overload
    def __init__(self, value: int, formatted_value: str) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, value: float, formatted_value: str) -> None: ...
    @overload
    def __init__(self, symbol: Symbol) -> None: ...
    @property
    def float(self) -> float: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_float(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_string(self) -> bool: ...
    @property
    def is_symbol(self) -> bool: ...
    @property
    def pure_text(self) -> str: ...
    @property
    def string(self) -> str: ...
    @property
    def symbol(self) -> Symbol: ...
    @property
    def text(self) -> str: ...
    @property
    def uint(self) -> int: ...
    @property
    def bool(self) -> bool: ...
    @property
    def int(self) -> int: ...

class Location:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def begin(self) -> Position: ...
    @property
    def end(self) -> Position: ...
    @property
    def file_path(self) -> str: ...
    @property
    def line_number(self) -> int: ...
    @property
    def text(self) -> str: ...

class LtExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class MatchesExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class Meta:
    key: str
    value: Literal
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def token_key(self) -> Token: ...
    @property
    def token_value(self) -> Token: ...

class MinusExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ModifyingVisitor(Visitor):
    def __init__(self) -> None: ...
    def cleanup_tokenstreams(self, context: TokenStreamContext, new_expression: Expression) -> None: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StringAtExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StringInRangeExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StringOffsetExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StringLengthExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: NotExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: DefinedExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: PercentualExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: UnaryMinusExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: BitwiseNotExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: AndExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: OrExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: LtExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: GtExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: LeExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: GeExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: EqExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: NeqExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ContainsExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: MatchesExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IcontainsExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IendsWithExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IequalsExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IstartsWithExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StartsWithExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: EndsWithExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: PlusExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: MinusExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: MultiplyExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: DivideExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ModuloExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: BitwiseXorExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: BitwiseAndExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: BitwiseOrExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ShiftLeftExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ShiftRightExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ForDictExpression, variable_result: Union[Expression,VisitAction], iterable_result: Union[Expression,VisitAction], body_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ForArrayExpression, variable_result: Union[Expression,VisitAction], iterable_result: Union[Expression,VisitAction], body_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ForStringExpression, variable_result: Union[Expression,VisitAction], iterable_result: Union[Expression,VisitAction], body_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: OfExpression, variable_result: Union[Expression,VisitAction], iterable_result: Union[Expression,VisitAction], body_result: Union[Expression,VisitAction], range_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IterableExpression, results: List[Union[Expression,VisitAction]]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: SetExpression, results: List[Union[Expression,VisitAction]]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: RangeExpression, left_result: Union[Expression,VisitAction], right_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: StructAccessExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ArrayAccessExpression, array_result: Union[Expression,VisitAction], accessor_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: FunctionCallExpression, function_result: Union[Expression,VisitAction], argument_results: List[Union[Expression,VisitAction]]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: ParenthesesExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: IntFunctionExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: VariableDefExpression, result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    @overload
    def default_handler(self, context: TokenStreamContext, expr: WithExpression, variable_results: List[Union[Expression,VisitAction]], body_result: Union[Expression,VisitAction]) -> Union[Expression,VisitAction]: ...
    def modify(self, expr: Expression, when_deleted: Expression = ...) -> Expression: ...
    def visit_AllExpression(self, expr: AllExpression) -> Union[Expression,VisitAction]: ...
    def visit_AndExpression(self, expr: AndExpression) -> Union[Expression,VisitAction]: ...
    def visit_AnyExpression(self, expr: AnyExpression) -> Union[Expression,VisitAction]: ...
    def visit_ArrayAccessExpression(self, expr: ArrayAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseAndExpression(self, expr: BitwiseAndExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseNotExpression(self, expr: BitwiseNotExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseOrExpression(self, expr: BitwiseOrExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseXorExpression(self, expr: BitwiseXorExpression) -> Union[Expression,VisitAction]: ...
    def visit_BoolLiteralExpression(self, expr: BoolLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_ContainsExpression(self, expr: ContainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_DefinedExpression(self, expr: DefinedExpression) -> Union[Expression,VisitAction]: ...
    def visit_DivideExpression(self, expr: DivideExpression) -> Union[Expression,VisitAction]: ...
    def visit_DoubleLiteralExpression(self, expr: DoubleLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_EndsWithExpression(self, expr: EndsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_EntrypointExpression(self, expr: EntrypointExpression) -> Union[Expression,VisitAction]: ...
    def visit_EqExpression(self, expr: EqExpression) -> Union[Expression,VisitAction]: ...
    def visit_FilesizeExpression(self, expr: FilesizeExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForArrayExpression(self, expr: ForArrayExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForDictExpression(self, expr: ForDictExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForStringExpression(self, expr: ForStringExpression) -> Union[Expression,VisitAction]: ...
    def visit_FunctionCallExpression(self, expr: FunctionCallExpression) -> Union[Expression,VisitAction]: ...
    def visit_GeExpression(self, expr: GeExpression) -> Union[Expression,VisitAction]: ...
    def visit_GtExpression(self, expr: GtExpression) -> Union[Expression,VisitAction]: ...
    def visit_IcontainsExpression(self, expr: IcontainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdExpression(self, expr: IdExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdWildcardExpression(self, expr: IdWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_IendsWithExpression(self, expr: IendsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IequalsExpression(self, expr: IequalsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntFunctionExpression(self, expr: IntFunctionExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntLiteralExpression(self, expr: IntLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_IstartsWithExpression(self, expr: IstartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IterableExpression(self, expr: IterableExpression) -> Union[Expression,VisitAction]: ...
    def visit_LeExpression(self, expr: LeExpression) -> Union[Expression,VisitAction]: ...
    def visit_LtExpression(self, expr: LtExpression) -> Union[Expression,VisitAction]: ...
    def visit_MatchesExpression(self, expr: MatchesExpression) -> Union[Expression,VisitAction]: ...
    def visit_MinusExpression(self, expr: MinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_ModuloExpression(self, expr: ModuloExpression) -> Union[Expression,VisitAction]: ...
    def visit_MultiplyExpression(self, expr: MultiplyExpression) -> Union[Expression,VisitAction]: ...
    def visit_NeqExpression(self, expr: NeqExpression) -> Union[Expression,VisitAction]: ...
    def visit_NoneExpression(self, expr: NoneExpression) -> Union[Expression,VisitAction]: ...
    def visit_NotExpression(self, expr: NotExpression) -> Union[Expression,VisitAction]: ...
    def visit_OfExpression(self, expr: OfExpression) -> Union[Expression,VisitAction]: ...
    def visit_OrExpression(self, expr: OrExpression) -> Union[Expression,VisitAction]: ...
    def visit_ParenthesesExpression(self, expr: ParenthesesExpression) -> Union[Expression,VisitAction]: ...
    def visit_PercentualExpression(self, expr: PercentualExpression) -> Union[Expression,VisitAction]: ...
    def visit_PlusExpression(self, expr: PlusExpression) -> Union[Expression,VisitAction]: ...
    def visit_RangeExpression(self, expr: RangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_RegexpExpression(self, expr: RegexpExpression) -> Union[Expression,VisitAction]: ...
    def visit_SetExpression(self, expr: SetExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftLeftExpression(self, expr: ShiftLeftExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftRightExpression(self, expr: ShiftRightExpression) -> Union[Expression,VisitAction]: ...
    def visit_StartsWithExpression(self, expr: StartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringAtExpression(self, expr: StringAtExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringCountExpression(self, expr: StringCountExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringExpression(self, expr: StringExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringInRangeExpression(self, expr: StringInRangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLengthExpression(self, expr: StringLengthExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLiteralExpression(self, expr: StringLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringOffsetExpression(self, expr: StringOffsetExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringWildcardExpression(self, expr: StringWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_StructAccessExpression(self, expr: StructAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_ThemExpression(self, expr: ThemExpression) -> Union[Expression,VisitAction]: ...
    def visit_UnaryMinusExpression(self, expr: UnaryMinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_VariableDefExpression(self, expr: VariableDefExpression) -> Union[Expression,VisitAction]: ...
    def visit_WithExpression(self, expr: WithExpression) -> Union[Expression,VisitAction]: ...

class Module:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def structure(self) -> StructureSymbol: ...

class ModuloExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class MultiplyExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class NeqExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class NocaseStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...

class NoneExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class NotExpression(UnaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ObservingRegexpVisitor(RegexpVisitor):
    def __init__(self) -> None: ...
    def observe(self, unit: RegexpUnit) -> Union[RegexpUnit,float]: ...
    def visit_RegexpAnyChar(self, unit: RegexpAnyChar) -> Union[RegexpUnit,float]: ...
    def visit_RegexpClass(self, unit: RegexpClass) -> Union[RegexpUnit,float]: ...
    def visit_RegexpConcat(self, unit: RegexpConcat) -> Union[RegexpUnit,float]: ...
    def visit_RegexpDigit(self, unit: RegexpDigit) -> Union[RegexpUnit,float]: ...
    def visit_RegexpEndOfLine(self, unit: RegexpEndOfLine) -> Union[RegexpUnit,float]: ...
    def visit_RegexpGroup(self, unit: RegexpGroup) -> Union[RegexpUnit,float]: ...
    def visit_RegexpIteration(self, unit: RegexpIteration) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonDigit(self, unit: RegexpNonDigit) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonSpace(self, unit: RegexpNonSpace) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonWordBoundary(self, unit: RegexpNonWordBoundary) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonWordChar(self, unit: RegexpNonWordChar) -> Union[RegexpUnit,float]: ...
    def visit_RegexpOptional(self, unit: RegexpOptional) -> Union[RegexpUnit,float]: ...
    def visit_RegexpOr(self, unit: RegexpOr) -> Union[RegexpUnit,float]: ...
    def visit_RegexpPositiveIteration(self, unit: RegexpPositiveIteration) -> Union[RegexpUnit,float]: ...
    def visit_RegexpRange(self, unit: RegexpRange) -> Union[RegexpUnit,float]: ...
    def visit_RegexpSpace(self, unit: RegexpSpace) -> Union[RegexpUnit,float]: ...
    def visit_RegexpStartOfLine(self, unit: RegexpStartOfLine) -> Union[RegexpUnit,float]: ...
    def visit_RegexpText(self, unit: RegexpText) -> Union[RegexpUnit,float]: ...
    def visit_RegexpWordBoundary(self, unit: RegexpWordBoundary) -> Union[RegexpUnit,float]: ...
    def visit_RegexpWordChar(self, unit: RegexpWordChar) -> Union[RegexpUnit,float]: ...

class ObservingVisitor(Visitor):
    def __init__(self) -> None: ...
    def observe(self, expr: Expression) -> None: ...
    def visit_AllExpression(self, expr: AllExpression) -> Union[Expression,VisitAction]: ...
    def visit_AndExpression(self, expr: AndExpression) -> Union[Expression,VisitAction]: ...
    def visit_AnyExpression(self, expr: AnyExpression) -> Union[Expression,VisitAction]: ...
    def visit_ArrayAccessExpression(self, expr: ArrayAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseAndExpression(self, expr: BitwiseAndExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseNotExpression(self, expr: BitwiseNotExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseOrExpression(self, expr: BitwiseOrExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseXorExpression(self, expr: BitwiseXorExpression) -> Union[Expression,VisitAction]: ...
    def visit_BoolLiteralExpression(self, expr: BoolLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_ContainsExpression(self, expr: ContainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_DefinedExpression(self, expr: DefinedExpression) -> Union[Expression,VisitAction]: ...
    def visit_DivideExpression(self, expr: DivideExpression) -> Union[Expression,VisitAction]: ...
    def visit_DoubleLiteralExpression(self, expr: DoubleLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_EndsWithExpression(self, expr: EndsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_EntrypointExpression(self, expr: EntrypointExpression) -> Union[Expression,VisitAction]: ...
    def visit_EqExpression(self, expr: EqExpression) -> Union[Expression,VisitAction]: ...
    def visit_FilesizeExpression(self, expr: FilesizeExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForArrayExpression(self, expr: ForArrayExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForDictExpression(self, expr: ForDictExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForStringExpression(self, expr: ForStringExpression) -> Union[Expression,VisitAction]: ...
    def visit_FunctionCallExpression(self, expr: FunctionCallExpression) -> Union[Expression,VisitAction]: ...
    def visit_GeExpression(self, expr: GeExpression) -> Union[Expression,VisitAction]: ...
    def visit_GtExpression(self, expr: GtExpression) -> Union[Expression,VisitAction]: ...
    def visit_IcontainsExpression(self, expr: IcontainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdExpression(self, expr: IdExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdWildcardExpression(self, expr: IdWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_IendsWithExpression(self, expr: IendsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IequalsExpression(self, expr: IequalsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntFunctionExpression(self, expr: IntFunctionExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntLiteralExpression(self, expr: IntLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_IstartsWithExpression(self, expr: IstartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IterableExpression(self, expr: IterableExpression) -> Union[Expression,VisitAction]: ...
    def visit_LeExpression(self, expr: LeExpression) -> Union[Expression,VisitAction]: ...
    def visit_LtExpression(self, expr: LtExpression) -> Union[Expression,VisitAction]: ...
    def visit_MatchesExpression(self, expr: MatchesExpression) -> Union[Expression,VisitAction]: ...
    def visit_MinusExpression(self, expr: MinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_ModuloExpression(self, expr: ModuloExpression) -> Union[Expression,VisitAction]: ...
    def visit_MultiplyExpression(self, expr: MultiplyExpression) -> Union[Expression,VisitAction]: ...
    def visit_NeqExpression(self, expr: NeqExpression) -> Union[Expression,VisitAction]: ...
    def visit_NoneExpression(self, expr: NoneExpression) -> Union[Expression,VisitAction]: ...
    def visit_NotExpression(self, expr: NotExpression) -> Union[Expression,VisitAction]: ...
    def visit_OfExpression(self, expr: OfExpression) -> Union[Expression,VisitAction]: ...
    def visit_OrExpression(self, expr: OrExpression) -> Union[Expression,VisitAction]: ...
    def visit_ParenthesesExpression(self, expr: ParenthesesExpression) -> Union[Expression,VisitAction]: ...
    def visit_PercentualExpression(self, expr: PercentualExpression) -> Union[Expression,VisitAction]: ...
    def visit_PlusExpression(self, expr: PlusExpression) -> Union[Expression,VisitAction]: ...
    def visit_RangeExpression(self, expr: RangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_RegexpExpression(self, expr: RegexpExpression) -> Union[Expression,VisitAction]: ...
    def visit_SetExpression(self, expr: SetExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftLeftExpression(self, expr: ShiftLeftExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftRightExpression(self, expr: ShiftRightExpression) -> Union[Expression,VisitAction]: ...
    def visit_StartsWithExpression(self, expr: StartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringAtExpression(self, expr: StringAtExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringCountExpression(self, expr: StringCountExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringExpression(self, expr: StringExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringInRangeExpression(self, expr: StringInRangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLengthExpression(self, expr: StringLengthExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLiteralExpression(self, expr: StringLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringOffsetExpression(self, expr: StringOffsetExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringWildcardExpression(self, expr: StringWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_StructAccessExpression(self, expr: StructAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_ThemExpression(self, expr: ThemExpression) -> Union[Expression,VisitAction]: ...
    def visit_UnaryMinusExpression(self, expr: UnaryMinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_VariableDefExpression(self, expr: VariableDefExpression) -> Union[Expression,VisitAction]: ...
    def visit_WithExpression(self, expr: WithExpression) -> Union[Expression,VisitAction]: ...

class OfExpression(ForExpression):
    range: Expression
    location: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class OrExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ParenthesesExpression(Expression):
    enclosed_expr: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class ParserError(Exception): ...

class ParserMode:
    __members__: ClassVar[dict] = ...  # read-only
    DeferredInclude: ClassVar[ParserMode] = ...
    IncludeGuarded: ClassVar[ParserMode] = ...
    Incomplete: ClassVar[ParserMode] = ...
    Regular: ClassVar[ParserMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PercentualExpression(UnaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class PlainString(String):
    def __init__(self, *args, **kwargs) -> None: ...

class PlusExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class Position:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def column(self) -> int: ...
    @property
    def line(self) -> int: ...

class PrivateStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...

class RangeExpression(Expression):
    high: Expression
    low: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class ReferenceSymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def symbol(self) -> Symbol: ...

class Regexp(String):
    unit: RegexpUnit
    def __init__(self, *args, **kwargs) -> None: ...
    def clone(self, target: TokenStream) -> Regexp: ...
    @property
    def suffix_modifiers(self) -> str: ...

class RegexpAnyChar(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpClass(RegexpUnit):
    characters: str
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def is_negative(self) -> bool: ...

class RegexpConcat(RegexpUnit):
    units: List[RegexpUnit]
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpDigit(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpEndOfLine(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpExpression(Expression):
    regexp_string: Regexp
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpGroup(RegexpUnit):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def unit(self) -> RegexpUnit: ...

class RegexpIteration(RegexpOperation):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpNonDigit(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpNonSpace(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpNonWordBoundary(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpNonWordChar(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpOperation(RegexpUnit):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def is_greedy(self) -> bool: ...
    @property
    def operand(self) -> RegexpUnit: ...
    @property
    def operation(self) -> str: ...

class RegexpOptional(RegexpOperation):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpOr(RegexpUnit):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def left(self) -> RegexpUnit: ...
    @property
    def right(self) -> RegexpUnit: ...

class RegexpPositiveIteration(RegexpOperation):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpRange(RegexpOperation):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def range(self) -> Tuple[Optional[int],Optional[int]]: ...

class RegexpSpace(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpStartOfLine(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpText(RegexpUnit):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def text(self) -> str: ...

class RegexpUnit:
    def __init__(self, *args, **kwargs) -> None: ...
    def accept(self, visitor: RegexpVisitor) -> Union[RegexpUnit,float]: ...
    @property
    def text(self) -> str: ...

class RegexpVisitor:
    def __init__(self) -> None: ...
    def visit_RegexpAnyChar(self, unit: RegexpAnyChar) -> Union[RegexpUnit,float]: ...
    def visit_RegexpClass(self, unit: RegexpClass) -> Union[RegexpUnit,float]: ...
    def visit_RegexpConcat(self, unit: RegexpConcat) -> Union[RegexpUnit,float]: ...
    def visit_RegexpDigit(self, unit: RegexpDigit) -> Union[RegexpUnit,float]: ...
    def visit_RegexpEndOfLine(self, unit: RegexpEndOfLine) -> Union[RegexpUnit,float]: ...
    def visit_RegexpGroup(self, unit: RegexpGroup) -> Union[RegexpUnit,float]: ...
    def visit_RegexpIteration(self, unit: RegexpIteration) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonDigit(self, unit: RegexpNonDigit) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonSpace(self, unit: RegexpNonSpace) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonWordBoundary(self, unit: RegexpNonWordBoundary) -> Union[RegexpUnit,float]: ...
    def visit_RegexpNonWordChar(self, unit: RegexpNonWordChar) -> Union[RegexpUnit,float]: ...
    def visit_RegexpOptional(self, unit: RegexpOptional) -> Union[RegexpUnit,float]: ...
    def visit_RegexpOr(self, unit: RegexpOr) -> Union[RegexpUnit,float]: ...
    def visit_RegexpPositiveIteration(self, unit: RegexpPositiveIteration) -> Union[RegexpUnit,float]: ...
    def visit_RegexpRange(self, unit: RegexpRange) -> Union[RegexpUnit,float]: ...
    def visit_RegexpSpace(self, unit: RegexpSpace) -> Union[RegexpUnit,float]: ...
    def visit_RegexpStartOfLine(self, unit: RegexpStartOfLine) -> Union[RegexpUnit,float]: ...
    def visit_RegexpText(self, unit: RegexpText) -> Union[RegexpUnit,float]: ...
    def visit_RegexpWordBoundary(self, unit: RegexpWordBoundary) -> Union[RegexpUnit,float]: ...
    def visit_RegexpWordChar(self, unit: RegexpWordChar) -> Union[RegexpUnit,float]: ...

class RegexpWordBoundary(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class RegexpWordChar(RegexpText):
    def __init__(self, *args, **kwargs) -> None: ...

class Rule:
    condition: Expression
    metas: List[Meta]
    modifier: RuleModifier
    name: str
    tags: List[str]
    variables: List[Variable]
    def __init__(self, *args, **kwargs) -> None: ...
    def add_meta(self, name: str, value: Literal) -> None: ...
    def add_tag(self, tag: str) -> None: ...
    def get_meta_with_name(self, name: str) -> Optional[Meta]: ...
    def remove_metas(self, name: str) -> None: ...
    def remove_string(self, id: str) -> None: ...
    def remove_tags(self, tag: str) -> None: ...
    def remove_variables(self) -> None: ...
    @property
    def is_global(self) -> bool: ...
    @property
    def is_private(self) -> bool: ...
    @property
    def location(self) -> Location: ...
    @property
    def strings(self) -> List[String]: ...
    @property
    def symbol(self) -> Symbol: ...
    @property
    def text(self) -> str: ...
    @property
    def token_first(self) -> Token: ...
    @property
    def token_last(self) -> Token: ...

class RuleModifier:
    __members__: ClassVar[dict] = ...  # read-only
    Empty: ClassVar[RuleModifier] = ...
    Global: ClassVar[RuleModifier] = ...
    Private: ClassVar[RuleModifier] = ...
    PrivateGlobal: ClassVar[RuleModifier] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SetExpression(Expression):
    elements: List[Expression]
    def __init__(self, *args, **kwargs) -> None: ...

class ShiftLeftExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class ShiftRightExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class StartsWithExpression(BinaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class String:
    def __init__(self, *args, **kwargs) -> None: ...
    def remove_modifiers(self) -> None: ...
    @property
    def identifier(self) -> str: ...
    @property
    def is_ascii(self) -> bool: ...
    @property
    def is_base64(self) -> bool: ...
    @property
    def is_base64_wide(self) -> bool: ...
    @property
    def is_fullword(self) -> bool: ...
    @property
    def is_hex(self) -> bool: ...
    @property
    def is_nocase(self) -> bool: ...
    @property
    def is_plain(self) -> bool: ...
    @property
    def is_private(self) -> bool: ...
    @property
    def is_regexp(self) -> bool: ...
    @property
    def is_wide(self) -> bool: ...
    @property
    def is_xor(self) -> bool: ...
    @property
    def location(self) -> Location: ...
    @property
    def modifiers(self) -> List[StringModifier]: ...
    @property
    def modifiers_text(self) -> str: ...
    @property
    def pure_text(self) -> bytes: ...
    @property
    def text(self) -> str: ...
    @property
    def token_assign(self) -> Token: ...
    @property
    def token_first(self) -> Token: ...
    @property
    def token_id(self) -> Token: ...
    @property
    def token_last(self) -> Token: ...
    @property
    def type(self) -> StringType: ...

class StringAtExpression(Expression):
    at_expr: Expression
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class StringCountExpression(Expression):
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class StringExpression(Expression):
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class StringInRangeExpression(Expression):
    id: str
    range_expr: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class StringLengthExpression(Expression):
    id: str
    index_expr: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class StringLiteralExpression(_StringLiteralExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class StringModifier:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def is_ascii(self) -> bool: ...
    @property
    def is_base64(self) -> bool: ...
    @property
    def is_base64_wide(self) -> bool: ...
    @property
    def is_fullword(self) -> bool: ...
    @property
    def is_nocase(self) -> bool: ...
    @property
    def is_private(self) -> bool: ...
    @property
    def is_wide(self) -> bool: ...
    @property
    def is_xor(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def type(self) -> StringModifierType: ...

class StringModifierType:
    __members__: ClassVar[dict] = ...  # read-only
    Ascii: ClassVar[StringModifierType] = ...
    Base64: ClassVar[StringModifierType] = ...
    Base64Wide: ClassVar[StringModifierType] = ...
    Fullword: ClassVar[StringModifierType] = ...
    Nocase: ClassVar[StringModifierType] = ...
    Private: ClassVar[StringModifierType] = ...
    Wide: ClassVar[StringModifierType] = ...
    Xor: ClassVar[StringModifierType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class StringOffsetExpression(Expression):
    id: str
    index_expr: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class StringType:
    __members__: ClassVar[dict] = ...  # read-only
    Hex: ClassVar[StringType] = ...
    Plain: ClassVar[StringType] = ...
    Regexp: ClassVar[StringType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class StringWildcardExpression(Expression):
    id: str
    def __init__(self, *args, **kwargs) -> None: ...

class StructAccessExpression(IdExpression):
    structure: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class StructureSymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_attribute(self, name: str) -> Optional[Symbol]: ...
    @property
    def attributes(self) -> Dict[str,Symbol]: ...

class Symbol:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def data_type(self) -> ExpressionType: ...
    @property
    def documentation(self) -> str: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def is_dictionary(self) -> bool: ...
    @property
    def is_function(self) -> bool: ...
    @property
    def is_reference(self) -> bool: ...
    @property
    def is_structure(self) -> bool: ...
    @property
    def is_value(self) -> bool: ...
    @property
    def name(self) -> str: ...

class ThemExpression(KeywordExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class Token:
    def __init__(self, type: TokenType, literal: Literal) -> None: ...
    @property
    def float(self) -> float: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_float(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_string(self) -> bool: ...
    @property
    def is_symbol(self) -> bool: ...
    @property
    def literal(self) -> Literal: ...
    @property
    def literal_reference(self) -> Literal: ...
    @property
    def location(self) -> Location: ...
    @property
    def pure_text(self) -> str: ...
    @property
    def string(self) -> str: ...
    @property
    def symbol(self) -> Symbol: ...
    @property
    def text(self) -> str: ...
    @property
    def type(self) -> TokenType: ...
    @property
    def uint(self) -> int: ...
    @property
    def bool(self) -> bool: ...
    @property
    def int(self) -> int: ...

class TokenIt:
    def __init__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def decrement(self) -> None: ...
    def increment(self) -> None: ...
    def next(self) -> TokenIt: ...
    def previous(self) -> TokenIt: ...
    @property
    def value(self) -> Token: ...

class TokenStream:
    def __init__(self) -> None: ...
    def comment_before_token(self, message: str, insert_before: TokenIt, multiline: bool = ..., indent: str = ..., linebreak: bool = ...) -> None: ...
    def erase(self, itr: TokenIt) -> TokenIt: ...
    def erase_range(self, first: TokenIt, last: TokenIt) -> TokenIt: ...
    def find(self, type: TokenType) -> TokenIt: ...
    def find_range(self, type: TokenType, start: TokenIt, stop: TokenIt) -> TokenIt: ...
    def insert(self, before: TokenIt, type: TokenType, literal: Literal) -> TokenIt: ...
    @property
    def back(self) -> Token: ...
    @property
    def begin(self) -> TokenIt: ...
    @property
    def empty(self) -> bool: ...
    @property
    def end(self) -> TokenIt: ...
    @property
    def front(self) -> Token: ...
    @property
    def size(self) -> int: ...
    @property
    def tokens(self) -> List[Token]: ...
    @property
    def tokens_as_text(self) -> List[str]: ...

class TokenStreamContext:
    def __init__(self, expr: Expression) -> None: ...

class TokenType:
    __members__: ClassVar[dict] = ...  # read-only
    All: ClassVar[TokenType] = ...
    And: ClassVar[TokenType] = ...
    Any: ClassVar[TokenType] = ...
    ArraySymbol: ClassVar[TokenType] = ...
    Ascii: ClassVar[TokenType] = ...
    Assign: ClassVar[TokenType] = ...
    Base64: ClassVar[TokenType] = ...
    Base64Wide: ClassVar[TokenType] = ...
    BitwiseAnd: ClassVar[TokenType] = ...
    BitwiseNot: ClassVar[TokenType] = ...
    BitwiseOr: ClassVar[TokenType] = ...
    BitwiseXor: ClassVar[TokenType] = ...
    BoolFalse: ClassVar[TokenType] = ...
    BoolTrue: ClassVar[TokenType] = ...
    Colon: ClassVar[TokenType] = ...
    ColonBeforeNewline: ClassVar[TokenType] = ...
    Comma: ClassVar[TokenType] = ...
    Comment: ClassVar[TokenType] = ...
    Condition: ClassVar[TokenType] = ...
    Contains: ClassVar[TokenType] = ...
    Dash: ClassVar[TokenType] = ...
    Defined: ClassVar[TokenType] = ...
    DictionarySymbol: ClassVar[TokenType] = ...
    Divide: ClassVar[TokenType] = ...
    Dot: ClassVar[TokenType] = ...
    Double: ClassVar[TokenType] = ...
    DoubleDot: ClassVar[TokenType] = ...
    EndsWith: ClassVar[TokenType] = ...
    Entrypoint: ClassVar[TokenType] = ...
    Eq: ClassVar[TokenType] = ...
    Filesize: ClassVar[TokenType] = ...
    For: ClassVar[TokenType] = ...
    Fullword: ClassVar[TokenType] = ...
    FunctionCallLp: ClassVar[TokenType] = ...
    FunctionCallRp: ClassVar[TokenType] = ...
    FunctionSymbol: ClassVar[TokenType] = ...
    Ge: ClassVar[TokenType] = ...
    Global: ClassVar[TokenType] = ...
    Gt: ClassVar[TokenType] = ...
    HexAlt: ClassVar[TokenType] = ...
    HexAltLeftBracket: ClassVar[TokenType] = ...
    HexAltRightBracket: ClassVar[TokenType] = ...
    HexEndBracket: ClassVar[TokenType] = ...
    HexJumpFixed: ClassVar[TokenType] = ...
    HexJumpLeftBracket: ClassVar[TokenType] = ...
    HexJumpRightBracket: ClassVar[TokenType] = ...
    HexNibble: ClassVar[TokenType] = ...
    HexStartBracket: ClassVar[TokenType] = ...
    HexWildcard: ClassVar[TokenType] = ...
    HexWildcardHigh: ClassVar[TokenType] = ...
    HexWildcardLow: ClassVar[TokenType] = ...
    Icontains: ClassVar[TokenType] = ...
    Id: ClassVar[TokenType] = ...
    IdWildcard: ClassVar[TokenType] = ...
    IendsWith: ClassVar[TokenType] = ...
    Iequals: ClassVar[TokenType] = ...
    ImportKeyword: ClassVar[TokenType] = ...
    ImportModule: ClassVar[TokenType] = ...
    IncludeDirective: ClassVar[TokenType] = ...
    IncludePath: ClassVar[TokenType] = ...
    Integer: ClassVar[TokenType] = ...
    IntegerFunction: ClassVar[TokenType] = ...
    Invalid: ClassVar[TokenType] = ...
    IstartsWith: ClassVar[TokenType] = ...
    Lcb: ClassVar[TokenType] = ...
    Le: ClassVar[TokenType] = ...
    Lp: ClassVar[TokenType] = ...
    LpEnumeration: ClassVar[TokenType] = ...
    LpWithSpaceAfter: ClassVar[TokenType] = ...
    LpWithSpaces: ClassVar[TokenType] = ...
    Lquote: ClassVar[TokenType] = ...
    Lsqb: ClassVar[TokenType] = ...
    LsqbEnumeration: ClassVar[TokenType] = ...
    Lt: ClassVar[TokenType] = ...
    Matches: ClassVar[TokenType] = ...
    Meta: ClassVar[TokenType] = ...
    MetaKey: ClassVar[TokenType] = ...
    MetaValue: ClassVar[TokenType] = ...
    Minus: ClassVar[TokenType] = ...
    Multiply: ClassVar[TokenType] = ...
    Neq: ClassVar[TokenType] = ...
    NewLine: ClassVar[TokenType] = ...
    Nocase: ClassVar[TokenType] = ...
    NoneToken: ClassVar[TokenType] = ...
    Not: ClassVar[TokenType] = ...
    Of: ClassVar[TokenType] = ...
    OnelineComment: ClassVar[TokenType] = ...
    OpAt: ClassVar[TokenType] = ...
    OpIn: ClassVar[TokenType] = ...
    Or: ClassVar[TokenType] = ...
    Percent: ClassVar[TokenType] = ...
    Plus: ClassVar[TokenType] = ...
    Private: ClassVar[TokenType] = ...
    PrivateStringModifier: ClassVar[TokenType] = ...
    Range: ClassVar[TokenType] = ...
    Rcb: ClassVar[TokenType] = ...
    ReferenceSymbol: ClassVar[TokenType] = ...
    RegexpChar: ClassVar[TokenType] = ...
    RegexpClassNegative: ClassVar[TokenType] = ...
    RegexpEndSlash: ClassVar[TokenType] = ...
    RegexpGreedy: ClassVar[TokenType] = ...
    RegexpIter: ClassVar[TokenType] = ...
    RegexpModifiers: ClassVar[TokenType] = ...
    RegexpOptional: ClassVar[TokenType] = ...
    RegexpOr: ClassVar[TokenType] = ...
    RegexpPiter: ClassVar[TokenType] = ...
    RegexpRange: ClassVar[TokenType] = ...
    RegexpStartSlash: ClassVar[TokenType] = ...
    RegexpText: ClassVar[TokenType] = ...
    Rp: ClassVar[TokenType] = ...
    RpEnumeration: ClassVar[TokenType] = ...
    RpWithSpaceBefore: ClassVar[TokenType] = ...
    RpWithSpaces: ClassVar[TokenType] = ...
    Rquote: ClassVar[TokenType] = ...
    Rsqb: ClassVar[TokenType] = ...
    RsqbEnumeration: ClassVar[TokenType] = ...
    Rule: ClassVar[TokenType] = ...
    RuleBegin: ClassVar[TokenType] = ...
    RuleEnd: ClassVar[TokenType] = ...
    RuleName: ClassVar[TokenType] = ...
    ShiftLeft: ClassVar[TokenType] = ...
    ShiftRight: ClassVar[TokenType] = ...
    Slash: ClassVar[TokenType] = ...
    StartsWith: ClassVar[TokenType] = ...
    StringCount: ClassVar[TokenType] = ...
    StringId: ClassVar[TokenType] = ...
    StringIdAfterNewline: ClassVar[TokenType] = ...
    StringIdWildcard: ClassVar[TokenType] = ...
    StringKey: ClassVar[TokenType] = ...
    StringLength: ClassVar[TokenType] = ...
    StringLiteral: ClassVar[TokenType] = ...
    StringOffset: ClassVar[TokenType] = ...
    Strings: ClassVar[TokenType] = ...
    StructureSymbol: ClassVar[TokenType] = ...
    Tag: ClassVar[TokenType] = ...
    Them: ClassVar[TokenType] = ...
    UnaryMinus: ClassVar[TokenType] = ...
    ValueSymbol: ClassVar[TokenType] = ...
    VariableKey: ClassVar[TokenType] = ...
    Variables: ClassVar[TokenType] = ...
    Wide: ClassVar[TokenType] = ...
    With: ClassVar[TokenType] = ...
    Xor: ClassVar[TokenType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class UnaryMinusExpression(UnaryOpExpression):
    def __init__(self, *args, **kwargs) -> None: ...

class UnaryOpExpression(Expression):
    operand: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class VariableDefExpression(Expression):
    name: str
    expression: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class ValueSymbol(Symbol):
    def __init__(self, *args, **kwargs) -> None: ...

class Variable:
    key: str
    value: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class VisitAction:
    __members__: ClassVar[dict] = ...  # read-only
    Delete: ClassVar[VisitAction] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class WithExpression(Expression):
    variables: List[Expression]
    body: Expression
    def __init__(self, *args, **kwargs) -> None: ...

class Visitor:
    def __init__(self) -> None: ...
    def visit_AllExpression(self, expr: AllExpression) -> Union[Expression,VisitAction]: ...
    def visit_AndExpression(self, expr: AndExpression) -> Union[Expression,VisitAction]: ...
    def visit_AnyExpression(self, expr: AnyExpression) -> Union[Expression,VisitAction]: ...
    def visit_ArrayAccessExpression(self, expr: ArrayAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseAndExpression(self, expr: BitwiseAndExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseNotExpression(self, expr: BitwiseNotExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseOrExpression(self, expr: BitwiseOrExpression) -> Union[Expression,VisitAction]: ...
    def visit_BitwiseXorExpression(self, expr: BitwiseXorExpression) -> Union[Expression,VisitAction]: ...
    def visit_BoolLiteralExpression(self, expr: BoolLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_ContainsExpression(self, expr: ContainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_DefinedExpression(self, expr: DefinedExpression) -> Union[Expression,VisitAction]: ...
    def visit_DivideExpression(self, expr: DivideExpression) -> Union[Expression,VisitAction]: ...
    def visit_DoubleLiteralExpression(self, expr: DoubleLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_EndsWithExpression(self, expr: EndsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_EntrypointExpression(self, expr: EntrypointExpression) -> Union[Expression,VisitAction]: ...
    def visit_EqExpression(self, expr: EqExpression) -> Union[Expression,VisitAction]: ...
    def visit_FilesizeExpression(self, expr: FilesizeExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForArrayExpression(self, expr: ForArrayExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForDictExpression(self, expr: ForDictExpression) -> Union[Expression,VisitAction]: ...
    def visit_ForStringExpression(self, expr: ForStringExpression) -> Union[Expression,VisitAction]: ...
    def visit_FunctionCallExpression(self, expr: FunctionCallExpression) -> Union[Expression,VisitAction]: ...
    def visit_GeExpression(self, expr: GeExpression) -> Union[Expression,VisitAction]: ...
    def visit_GtExpression(self, expr: GtExpression) -> Union[Expression,VisitAction]: ...
    def visit_IcontainsExpression(self, expr: IcontainsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdExpression(self, expr: IdExpression) -> Union[Expression,VisitAction]: ...
    def visit_IdWildcardExpression(self, expr: IdWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_IendsWithExpression(self, expr: IendsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IequalsExpression(self, expr: IequalsExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntFunctionExpression(self, expr: IntFunctionExpression) -> Union[Expression,VisitAction]: ...
    def visit_IntLiteralExpression(self, expr: IntLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_IstartsWithExpression(self, expr: IstartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_IterableExpression(self, expr: IterableExpression) -> Union[Expression,VisitAction]: ...
    def visit_LeExpression(self, expr: LeExpression) -> Union[Expression,VisitAction]: ...
    def visit_LtExpression(self, expr: LtExpression) -> Union[Expression,VisitAction]: ...
    def visit_MatchesExpression(self, expr: MatchesExpression) -> Union[Expression,VisitAction]: ...
    def visit_MinusExpression(self, expr: MinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_ModuloExpression(self, expr: ModuloExpression) -> Union[Expression,VisitAction]: ...
    def visit_MultiplyExpression(self, expr: MultiplyExpression) -> Union[Expression,VisitAction]: ...
    def visit_NeqExpression(self, expr: NeqExpression) -> Union[Expression,VisitAction]: ...
    def visit_NoneExpression(self, expr: NoneExpression) -> Union[Expression,VisitAction]: ...
    def visit_NotExpression(self, expr: NotExpression) -> Union[Expression,VisitAction]: ...
    def visit_OfExpression(self, expr: OfExpression) -> Union[Expression,VisitAction]: ...
    def visit_OrExpression(self, expr: OrExpression) -> Union[Expression,VisitAction]: ...
    def visit_ParenthesesExpression(self, expr: ParenthesesExpression) -> Union[Expression,VisitAction]: ...
    def visit_PercentualExpression(self, expr: PercentualExpression) -> Union[Expression,VisitAction]: ...
    def visit_PlusExpression(self, expr: PlusExpression) -> Union[Expression,VisitAction]: ...
    def visit_RangeExpression(self, expr: RangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_RegexpExpression(self, expr: RegexpExpression) -> Union[Expression,VisitAction]: ...
    def visit_SetExpression(self, expr: SetExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftLeftExpression(self, expr: ShiftLeftExpression) -> Union[Expression,VisitAction]: ...
    def visit_ShiftRightExpression(self, expr: ShiftRightExpression) -> Union[Expression,VisitAction]: ...
    def visit_StartsWithExpression(self, expr: StartsWithExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringAtExpression(self, expr: StringAtExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringCountExpression(self, expr: StringCountExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringExpression(self, expr: StringExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringInRangeExpression(self, expr: StringInRangeExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLengthExpression(self, expr: StringLengthExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringLiteralExpression(self, expr: StringLiteralExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringOffsetExpression(self, expr: StringOffsetExpression) -> Union[Expression,VisitAction]: ...
    def visit_StringWildcardExpression(self, expr: StringWildcardExpression) -> Union[Expression,VisitAction]: ...
    def visit_StructAccessExpression(self, expr: StructAccessExpression) -> Union[Expression,VisitAction]: ...
    def visit_ThemExpression(self, expr: ThemExpression) -> Union[Expression,VisitAction]: ...
    def visit_UnaryMinusExpression(self, expr: UnaryMinusExpression) -> Union[Expression,VisitAction]: ...
    def visit_VariableDefExpression(self, expr: VariableDefExpression) -> Union[Expression,VisitAction]: ...
    def visit_WithExpression(self, expr: WithExpression) -> Union[Expression,VisitAction]: ...

class WideStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...

class XorStringModifier(StringModifier):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def is_range(self) -> bool: ...
    @property
    def is_single_key(self) -> bool: ...

class YaraExpressionBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, expr: Expression) -> None: ...
    def access(self, name: str) -> YaraExpressionBuilder: ...
    def comment(self, message: str, multiline: bool = ..., indent: str = ..., linebreak: bool = ...) -> YaraExpressionBuilder: ...
    def comment_behind(self, message: str, multiline: bool = ..., indent: str = ..., linebreak: bool = ...) -> YaraExpressionBuilder: ...
    def contains(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def defined(self) -> YaraExpressionBuilder: ...
    def endswith(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def get(self) -> Expression: ...
    def icontains(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def iendswith(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def iequals(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def istartswith(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def matches(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def percent(self) -> YaraExpressionBuilder: ...
    def read_int16(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def read_int32(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def read_int8(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def read_uint16(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def read_uint32(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def read_uint8(self, endianness: IntFunctionEndianness) -> YaraExpressionBuilder: ...
    def startswith(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __add__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __and__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __call__(self, *args) -> YaraExpressionBuilder: ...
    def __ge__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __getitem__(self, index: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __gt__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __invert__(self) -> YaraExpressionBuilder: ...
    def __le__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __lshift__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __lt__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __mod__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __mul__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __neg__(self) -> YaraExpressionBuilder: ...
    def __or__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __rshift__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __sub__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __truediv__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
    def __xor__(self, other: YaraExpressionBuilder) -> YaraExpressionBuilder: ...

class YaraFile:
    def __init__(self, *args, **kwargs) -> None: ...
    def add_rule(self, rule: Rule) -> None: ...
    def deferred_includes(self) -> List[str]: ...
    def expand_rule_prefix_from_origin(self, prefix: str, origin: Rule) -> List[str]: ...
    def find_symbol(self, name: str) -> Optional[Symbol]: ...
    def insert_rule(self, position: int, rule: Rule) -> None: ...
    def remove_imports(self, pred: Callable[[Module], bool]) -> None: ...
    def remove_rules(self, pred: Callable[[Rule], bool]) -> None: ...
    @property
    def imports(self) -> List[Module]: ...
    @property
    def rules(self) -> List[Rule]: ...
    @property
    def text(self) -> str: ...
    @property
    def text_formatted(self) -> str: ...
    @property
    def tokenstream(self) -> TokenStream: ...

class YaraFileBuilder:
    def __init__(self, import_features: Features = ..., modules_directory: str = ...) -> None: ...
    def get(self, recheck: bool = ...) -> YaraFile: ...
    def with_module(self, name: str) -> YaraFileBuilder: ...
    def with_rule(self, rule: Rule) -> YaraFileBuilder: ...

class YaraHexStringBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, byte: int) -> None: ...
    @overload
    def __init__(self, bytes: List[int]) -> None: ...
    @overload
    def __init__(self, unit: HexStringUnit) -> None: ...
    @overload
    def __init__(self, units: List[HexStringUnit]) -> None: ...
    def add(self, unit: YaraHexStringBuilder) -> YaraHexStringBuilder: ...
    def get(self) -> HexString: ...

class YaraRuleBuilder:
    def __init__(self) -> None: ...
    def ascii(self) -> YaraRuleBuilder: ...
    def base64(self, *args) -> YaraRuleBuilder: ...
    def base64wide(self, *args) -> YaraRuleBuilder: ...
    def fullword(self) -> YaraRuleBuilder: ...
    def get(self) -> Rule: ...
    def nocase(self) -> YaraRuleBuilder: ...
    def private(self) -> YaraRuleBuilder: ...
    def wide(self) -> YaraRuleBuilder: ...
    def with_bool_meta(self, key: str, value: bool) -> YaraRuleBuilder: ...
    def with_bool_variable(self, key: str, value: bool) -> YaraRuleBuilder: ...
    def with_comment(self, comment: str, multiline: bool = ...) -> YaraRuleBuilder: ...
    def with_condition(self, condition: Expression) -> YaraRuleBuilder: ...
    def with_double_variable(self, key: str, value: float) -> YaraRuleBuilder: ...
    def with_hex_int_meta(self, key: str, value: int) -> YaraRuleBuilder: ...
    def with_hex_int_variable(self, key: str, value: int) -> YaraRuleBuilder: ...
    def with_hex_string(self, id: str, hex_string: HexString) -> YaraRuleBuilder: ...
    def with_int_meta(self, key: str, value: int) -> YaraRuleBuilder: ...
    def with_int_variable(self, key: str, value: int) -> YaraRuleBuilder: ...
    def with_modifier(self, modifier: RuleModifier) -> YaraRuleBuilder: ...
    def with_name(self, name: str) -> YaraRuleBuilder: ...
    def with_plain_string(self, id: str, value: str) -> YaraRuleBuilder: ...
    def with_regexp(self, id: str, value: str, suffix_mods: str = ...) -> YaraRuleBuilder: ...
    def with_string_meta(self, key: str, value: str) -> YaraRuleBuilder: ...
    def with_string_variable(self, key: str, value: str) -> YaraRuleBuilder: ...
    def with_struct_variable(self, key: str, value: str) -> YaraRuleBuilder: ...
    def with_tag(self, tag: str) -> YaraRuleBuilder: ...
    def with_uint_meta(self, key: str, value: int) -> YaraRuleBuilder: ...
    def with_uint_variable(self, key: str, value: int) -> YaraRuleBuilder: ...
    def xor(self, *args) -> YaraRuleBuilder: ...

class Yaramod:
    def __init__(self, import_features: Features = ..., modules_directory: str = ...) -> None: ...
    def parse_file(self, file_path: str, parser_mode: ParserMode = ...) -> YaraFile: ...
    def parse_string(self, str: str, parser_mode: ParserMode = ...) -> YaraFile: ...
    @property
    def modules(self) -> Dict[str,Module]: ...
    @property
    def yara_file(self) -> YaraFile: ...

class _BoolLiteralExpression(Expression):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def value(self) -> bool: ...

class _DoubleLiteralExpression(Expression):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def value(self) -> float: ...

class _IntLiteralExpression(Expression):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def value(self) -> int: ...

class _StringLiteralExpression(Expression):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def value(self) -> str: ...

def all() -> YaraExpressionBuilder: ...
def alt(units: List[YaraHexStringBuilder]) -> YaraHexStringBuilder: ...
def any() -> YaraExpressionBuilder: ...
def bool_val(value: bool) -> YaraExpressionBuilder: ...
@overload
def conjunction(terms: List[YaraExpressionBuilder], linebreaks: bool = ...) -> YaraExpressionBuilder: ...
@overload
def conjunction(terms: List[Tuple[YaraExpressionBuilder,str]]) -> YaraExpressionBuilder: ...
@overload
def disjunction(terms: List[YaraExpressionBuilder], linebreaks: bool = ...) -> YaraExpressionBuilder: ...
@overload
def disjunction(terms: List[Tuple[YaraExpressionBuilder,str]]) -> YaraExpressionBuilder: ...
def double_val(value: float) -> YaraExpressionBuilder: ...
def entrypoint() -> YaraExpressionBuilder: ...
def filesize() -> YaraExpressionBuilder: ...
@overload
def for_loop(spec: YaraExpressionBuilder, id1: str, id2: str, iterable: YaraExpressionBuilder, body: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
@overload
def for_loop(spec: YaraExpressionBuilder, id: str, iterable: YaraExpressionBuilder, body: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
@overload
def for_loop(spec: YaraExpressionBuilder, iterable: YaraExpressionBuilder, body: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def hex_int_val(value: int) -> YaraExpressionBuilder: ...
def id(name: str) -> YaraExpressionBuilder: ...
def int_val(value: int, mult: IntMultiplier = ...) -> YaraExpressionBuilder: ...
def iterable(elements: List[YaraExpressionBuilder]) -> YaraExpressionBuilder: ...
def jump_fixed(length: int) -> YaraHexStringBuilder: ...
def jump_range(low: int, high: int) -> YaraHexStringBuilder: ...
def jump_varying() -> YaraHexStringBuilder: ...
def jump_varying_range(max_length: int) -> YaraHexStringBuilder: ...
def match_at(id: str, at_expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def match_count(id: str) -> YaraExpressionBuilder: ...
def match_in_range(id: str, range_expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
@overload
def match_length(id: str) -> YaraExpressionBuilder: ...
@overload
def match_length(id: str, index: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
@overload
def match_offset(id: str) -> YaraExpressionBuilder: ...
@overload
def match_offset(id: str, index: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def not_(expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def not_byte(byte: int) -> YaraHexStringBuilder: ...
def not_wildcard_high(nibble: int) -> YaraHexStringBuilder: ...
def not_wildcard_low(nibble: int) -> YaraHexStringBuilder: ...
def of(spec: YaraExpressionBuilder, strings: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def of_in_range(spec: YaraExpressionBuilder, strings: YaraExpressionBuilder, range_expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def of_at(spec: YaraExpressionBuilder, strings: YaraExpressionBuilder, at_expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def paren(enclosed_expr: YaraExpressionBuilder, linebreaks: bool = ...) -> YaraExpressionBuilder: ...
def range(low: YaraExpressionBuilder, high: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def regexp(pattern: str, suffix_mods: str) -> YaraExpressionBuilder: ...
def set(elements: List[YaraExpressionBuilder]) -> YaraExpressionBuilder: ...
def string_ref(id: str) -> YaraExpressionBuilder: ...
def string_val(value: str) -> YaraExpressionBuilder: ...
def them() -> YaraExpressionBuilder: ...
def uint_val(value: int, mult: IntMultiplier = ...) -> YaraExpressionBuilder: ...
def var_def(name: str, expr: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
def wildcard() -> YaraHexStringBuilder: ...
def wildcard_high(nibble: int) -> YaraHexStringBuilder: ...
def wildcard_low(nibble: int) -> YaraHexStringBuilder: ...
def with_(variables: List[YaraExpressionBuilder], body: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
